prescolapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth.views import logout_then_login
from alumnos.views import Index ,AlumnoCreate, AlumnoReporte, busquedaTurores,ReporteNoChafa, busquedaAlumno,Detail_ninja, Update_Alumno, Detail_Alumno, AgregarAlumConEstilo, EvaluarAlumno, EvaDiario, detalleEvalSem, detalleDiario, DiarioReporte, EvaluacionReporte, reporteEvaluacionAlumno, reporteDiarioAlumno
from maestros.views import agregarMaestro, actualizarMaestro, MaestroReporte, buscarMaestros,DetalleMaestro, crearGrupo, buscarSinGrupo, buscarGrupo, GrupoReporte, infoGrupo, actualizaGrupo,buscarEnelGrupo
from padres.views import LogIn, Index2, login, addTutor, tutorAsign,updateTutores, TutoresReporte, Detail_Tutor, ActualizarTutores
#para las fotos
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'login/', login, name='login'),
    url(r'^$',Index, name='index'),
    url(r'^index2',Index2, name='index2'),
    #url para alumnos 
    url(r'^alumnos/detalles',AlumnoReporte.as_view(),name='alumnos_reporte'),
    url(r'^alumnos/agregar',AgregarAlumConEstilo.as_view(),name='alumnos_agregarxd'),
    #url(r'^alumnos/agregar2',AlumnoCreate.as_view(),name='alumnos_agregar'),
    url(r'^alumnos/paginador',ReporteNoChafa.as_view(),name='alumnos_pagina'),
    url(r'^cerrar', logout_then_login, name='logout' ),
    #url(r'^maestros/agregar', StudentSignUpView.as_view(), name='student_signup'),
    url(r'^tutores/busqueda',busquedaTurores,name='filtroTutores'),
    url(r'^alumnos/Buscar', busquedaAlumno, name='filtroAlumno'),
    path('detalleAlumno/<slug:slug>', Detail_ninja.as_view(), name='detail_view' ),
    url(r'^maestros/nuevo', agregarMaestro.as_view(), name="add_teacher"),
    url(r'^padres/agregar', addTutor.as_view(), name="AddTutor"),
    path('updateAlumno/<slug:slug>', Update_Alumno.as_view(), name="UpdateAlumno"),
    path('detalles/<slug:slug>', Detail_Alumno.as_view()),
    path('evaluar/<slug:slug>', EvaluarAlumno.as_view()),
    path('diario/<slug:slug>', EvaDiario.as_view()),
    path('addtutor/<slug:slug>', tutorAsign),
    path('Actualizar/Tutores', updateTutores),
    path('tutor/buscar', TutoresReporte.as_view(), name='reporteTutor'),
    path('detalles/tutor/<slug:slug>', Detail_Tutor),
    path('actualiza/tutor/<slug:slug>', ActualizarTutores),
    path('actualiza/maestro/<slug:slug>',actualizarMaestro),
    path('maestro/buscar', MaestroReporte.as_view(), name='reporteMaestro'),
    path('detalles/maestro/<slug:slug>', DetalleMaestro),
    path('maestros/busqueda/', buscarMaestros),
    path('grupo/crear', crearGrupo, name='crearGrupo'),
    path('alumnosNG/busqueda/', buscarSinGrupo),
    path('grupos/busqueda/', buscarGrupo),
    path('grupo/buscar', GrupoReporte.as_view(), name='reporteGrupo'),
    path('detalles/grupos/<slug:slug>',infoGrupo),
    path('actualiza/grupo/<slug:slug>', actualizaGrupo ),
    path('buscar/alumnosSG/<slug:slug>/', buscarEnelGrupo),
	path('detalle/evaluacion/semanal/<slug:slug>', detalleEvalSem),
    path('detalle/evaluacion/diario/<slug:slug>', detalleDiario),
    url(r'^reporte/diario', DiarioReporte.as_view(),name="reporteDiario"),
    url(r'^reporte/evaluacion', EvaluacionReporte.as_view(),name="reporteEvaluacion"),
    path('reporte/evallu/<slug:slug>', reporteEvaluacionAlumno),
    path('reporte/diarioalu/<slug:slug>', reporteDiarioAlumno),
    ]
#para las fotos
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

alumnos/models.py
from django.db import models
from padres.models import Tutor
from django.urls import reverse
import random, string
#from maestros.models import maestros
# Create your models here.

class alumnos(models.Model):
    alu_nombre = models.CharField(max_length = 400)
    alu_genero = models.CharField(max_length = 10,default="Masculino")
    alu_tutores = models.ManyToManyField(Tutor)
    alu_vigente = models.BooleanField(default = True)
    alu_fechaIngreso = models.DateField(auto_now_add = True, null=True)
    alu_observaciones = models.CharField(max_length = 2000, null=True)
    alu_foto = models.ImageField(upload_to='media/fotosAlu', null=True, default='media/default/default.jpeg')
    slug = models.SlugField(max_length=24, default=''.join(random.SystemRandom().choice(string.ascii_uppercase + string.digits) for _ in range(24)))
    
    def __str__(self):
        return self.alu_nombre

alumnos/views.py
from django.shortcuts import render
from alumnos.models import alumnos
from django.contrib.auth.models import User
from django.views.generic import CreateView, ListView,DetailView, UpdateView, DetailView, FormView
from alumnos.forms import Alumno_Form, Alumno_Chido, Alumno_Eva, Alumno_EvaDiario
from django.urls import reverse_lazy
from django.core import serializers
from django.http import JsonResponse, HttpResponse
from padres.models import Tutor, Profesor
from maestros.models import Evaluacion, grupos, DiarioTrabajo
import string
from datetime import date, timedelta, datetime

def get_week_days(year, week):
    d = date(year,1,1)
    if(d.weekday()>3):
        d = d+timedelta(7-d.weekday())
    else:
        d = d - timedelta(d.weekday())
    dlt = timedelta(days = (week-1)*7)
    return d + dlt,  d + dlt + timedelta(days=6)


def Index(request):
    user = request.user
    if user.is_active is True:
        if user.is_staff is False :
            if user.has_perm('padres.is_teacher'):
                yar = datetime.now().year
                today = date.today()
                wk = today.isocalendar()[1]
                inicio, fin = get_week_days(yar ,wk)
                prf = Profesor.objects.get(pro_nombre = user)
                grp = grupos.objects.select_related().filter(gru_maestro = prf)
                almGRUP = []
                for k in grp:
                    almGRUP.append({"Alumnos": k.gru_alumnos.all(), "Grupo": k.id})

                evaluacionesArray = []
                for j in range(len(almGRUP)):
                    kj = []
                    for hj in almGRUP[j]['Alumnos']:
                        kj.append(hj.id)

                    diarios = []
                    amevals = []
                    evalpos = []
                    evals =  Evaluacion.objects.filter(E_alumno__id__in = kj).filter(E_fecha__range = [inicio, fin])
                    for nh in evals:
                        amevals.append(nh.E_alumno.id)
                        evalpos.append({"IDA": nh.E_alumno.id, "EvaId": nh.id})

                    diar = DiarioTrabajo.objects.select_related().filter(DT_fecha = today).filter(DT_alumno__id__in = kj)
                    idDiar = []
                    aluDiar = []           
                    for ml in diar:
                        idDiar.append(ml.id)
                        aluDiar.append(ml.DT_alumno.id)

                    diarios.append({"Diario": idDiar, "Alumno": aluDiar})
                    evaluacionesArray.append({"Grupo": almGRUP[j]['Grupo'], "Alumnos": amevals, "EvalId": evalpos, "Diario": diarios})
                ctx = {"Perfil": prf, "Grupos": grp, "Evaluados": evaluacionesArray}
                print(ctx)
            if user.has_perm('padres.is_tutorr'):
                tur = Tutor.objects.get(tut_nombre = user)
                alm = alumnos.objects.filter(alu_tutores__in = [tur])
                ctx = {"Alumno":alm}        
            
            return render(request,'alumnos/index.html', ctx)
        else:
            return render(request,'alumnos/index.html')
        
    return render(request,'alumnos/index.html')

#import random, string
#x = ''.join(random.SystemRandom().choice(string.ascii_uppercase + string.digits) for _ in range(16 ))

#def Alumno_Formulario(request):
#	form = Alumno_Form(request.POST or None)
#	if request.method == "POST":
#		if form.is_valid():
#			form.save()
#	return render(request,'alumnos/formulario.html',{"form":form})

class AlumnoCreate(CreateView):
	model = alumnos
	fields = "__all__"
	template_name = "alumnos/crear.html"
	success_url = reverse_lazy("alumnos_reporte")

class AlumnoReporte(ListView):
	template_name = "alumnos/reporte.html"
	model = alumnos

class DiarioReporte(ListView):
    template_name="evaluaciones/reporteDiario.html"
    today = date.today()
    model = DiarioTrabajo
    queryset = DiarioTrabajo.objects.filter(DT_fecha__startswith=today)

class EvaluacionReporte(ListView):
    template_name="evaluaciones/reporteEvaluacion.html"
    model = Evaluacion
    date = date.today()
    start_week = date - timedelta(date.weekday())
    end_week = start_week + timedelta(7)
    queryset = Evaluacion.objects.filter(E_fecha__range= [start_week, end_week])

def busquedaTurores(request):
    if  request.method == 'GET':
        datos = []
        filtro = request.GET['filtro']
        data =  Tutor.objects.select_related().filter(tut_apellidos__contains = filtro)
        for dt in data:
            datos.append({"Usuario": str(dt.tut_nombre.username), 'Apellidos': str(dt.tut_apellidos), 'Numero':str(dt.tut_numero), 'Descripcion':str(dt.tut_descripcion)})

        data = serializers.serialize('json',data)
    else:
        data = ""
    return HttpResponse(str(datos))

class ReporteNoChafa(ListView):
	template_name="alumnos/reporte_no_chafa.html"
	model = alumnos #alumnos.object.all()
	paginate_by = 5

    #def get_context_data(self,**kwargs):
    #    obj = self.get_object()
    #    dic={
    #        "name:"obj.name.username,
    #        "aldea:"obj.aldea,
    #        "nature chakra:"obj.nature_chakra
    #    }
    #    return dic
    #
    #def render_to_response(self):
    #    return self
    #
def busquedaAlumno(request):
    if request.method == 'GET':
        filtro = request.GET['filtro']
        data = serializers.serialize('json', alumnos.objects.filter(alu_nombre__contains = filtro))
    else:
        data = ""
    return HttpResponse(data)

class Detail_ninja(DetailView):
    template_name="amunlos/detalleAlumno.html"
    model = alumnos
    
class Update_Alumno(UpdateView):
    template_name = 'alumnos/updateA.html'
    model = alumnos
    fields = '__all__'
    success_url = reverse_lazy('alumnos_reporte')
    
class Detail_Alumno(DetailView):
    template_name="alumnos/detalleAlumno.html"
    model = alumnos

class AgregarAlumConEstilo(FormView):
    template_name = "alumnos/crear.html"
    form_class = Alumno_Chido
    success_url = reverse_lazy('alumnos_reporte')
    
    def form_valid(self, form):
        alu = alumnos()
        alu.alu_nombre = form.cleaned_data['alu_nombre']
        alu.alu_genero = form.cleaned_data['alu_genero']
        #alu.alu_tutores = form.cleaned_data['alu_tutores']
        alu.save()
        gen = form.cleaned_data['alu_genero']
        if gen == 'Masculino':
            alu.alu_foto = 'media/default/boy.png'
        else:
            alu.alu_foto = 'media/default/girl.jpg'
        alu.alu_tutores.set(form.cleaned_data['alu_tutores'])
        alu.alu_vigente = form.cleaned_data['alu_vigente']
        alu.alu_fechaIngreso = form.cleaned_data['alu_fechaIngreso']
        alu.alu_observaciones = form.cleaned_data['alu_observaciones']
        alu.slug =form.cleaned_data['slug']
        alu.save()
        return super(AgregarAlumConEstilo,self).form_valid(form)

class EvaluarAlumno(FormView):
    template_name = "alumnos/evaluar.html"
    form_class = Alumno_Eva
    success_url = reverse_lazy('reporteEvaluacion')

    def get_context_data(self, *args, **kwargs):
        ctx = super(EvaluarAlumno, self).get_context_data(*args, **kwargs)
        #ctx['slug'] = self.kwargs['slug'] # or Tag.objects.get(slug=...)
        slug = self.kwargs['slug']
        ctx ['alumno'] = alumnos.objects.get(slug=slug)
        return ctx
    
    def form_valid(self, form):
        eva = Evaluacion()
        filtro = form.cleaned_data['E_maestro']
        maes = Profesor.objects.get(pro_nombre=filtro)
        eva.E_maestro = maes
        filtroalum = form.cleaned_data['E_alumno']
        alu = alumnos.objects.get(alu_nombre=filtroalum)
        eva.E_alumno = alu
        #eva = Evaluacion()
        #filtro = form.cleaned_data['E_maestro']
        #maeusr = User.objects.get(username = filtro)
        #maes = Profesor.objects.get(pro_nombre=maeusr)
        #eva.E_maestro = maes
        #filtroalum = form.cleaned_data['E_alumno']
        #alu = alumnos.objects.get(alu_nombre=filtroalum)
        #eva.E_alumno = alu
        eva.E_fecha = form.cleaned_data['E_fecha']
        eva.E_comparte = form.cleaned_data['E_comparte']
        eva.E_apoya =  form.cleaned_data['E_apoya']
        eva.E_pregunta =  form.cleaned_data['E_pregunta']
        eva.E_sugerencia =  form.cleaned_data['E_sugerencia']
        eva.E_controla = form.cleaned_data['E_controla']
        eva.E_cuida =  form.cleaned_data['E_cuida']
        eva.E_espera =  form.cleaned_data['E_espera']
        eva.E_negocia =  form.cleaned_data['E_negocia']
        eva.E_trabajaEquipo =  form.cleaned_data['E_trabajaEquipo']
        eva.E_respeta =  form.cleaned_data['E_respeta']
        eva.E_cuidadoso =  form.cleaned_data['E_cuidadoso']
        eva.E_involucra =  form.cleaned_data['E_involucra']
        eva.E_iniciativa =  form.cleaned_data['E_iniciativa']
        eva.E_riesgo =  form.cleaned_data['E_riesgo']
        eva.E_estrategias = form.cleaned_data['E_estrategias']
        eva.E_seExpresa =  form.cleaned_data['E_seExpresa']
        #lenguaje y comunicacion
        eva.E_mencionaNombre =  form.cleaned_data['E_mencionaNombre']
        eva.E_mencionaDomicilio =  form.cleaned_data['E_mencionaDomicilio']
        eva.E_expresaSentir  =  form.cleaned_data['E_expresaSentir']
        eva.E_exprasaSentimientos =  form.cleaned_data['E_exprasaSentimientos']
        eva.E_recuerdaSusesos =  form.cleaned_data['E_recuerdaSusesos']
        eva.E_solicitaPalabra =  form.cleaned_data['E_solicitaPalabra']
        eva.E_respetaTurno =  form.cleaned_data['E_respetaTurno']
        eva.E_explica =  form.cleaned_data['E_explica']
        eva.E_formulaPreguntas =  form.cleaned_data['E_formulaPreguntas']
        eva.E_comprendeTareas =  form.cleaned_data['E_comprendeTareas']
        eva.E_solicitaAyuda = form.cleaned_data['E_solicitaAyuda']
        eva.E_conversa = form.cleaned_data['E_conversa']
        eva.E_expresaInformacion = form.cleaned_data['E_expresaInformacion']
        eva.E_escucha = form.cleaned_data['E_escucha']

templates/alumnos/DetalleDiario.html
{% extends "base.html" %}
{% block title %}Informacion del alumno{% endblock %}
{% block content %}
<div class="container">

<div class="mt-4 mb-4 card border rounded border-warning" style="max-width:300px">
<img src="{{ object.alu_foto.url }}" class="card-img-top border-bottom"/>
    <div class="card-body border-bottom">
<h3 class="form-label text-center">Diario de trabajo</h3>
    </div>
    <div class="card-body">
        <div class="form-inline form-group">

            <h4 class="card-title">maestro: {{Diario.DT_maestro}}</h4>
            <h5 class="w-100"> 
            Alumno: {{Diario.DT_alumno}}</h5>
            <h6>Fecha de la evaluación: {{Diario.DT_fecha}}</h6>
            <p class="card-text">Descripción:{{Diario.DT_descripcion}}</p>
            <br>
            <p class="card-text">Actividad: {{Diario.DT_actividadApoyo}}</p>
            <br>
            <p class="card-text">
            Necesidades: {{Diario.DT_necesidades}}</p>
        </div>
    </div>

</div>
<button class="btn btn-danger" onclick="window.location.href = '/'">Volver</button>
</div>
{% endblock %}

templates/alumnos/alumnotutores.html
{% extends 'base.html' %}
{% block title %}Asignar tutores{% endblock %}
{% block content %}
<div class="mt-4 mb-4 card border rounded border-warning">
	<div class="container">
        <div class="card-body border-bottom">
			<h2 class="form-label text-center">Asignar tutores</h2>
			<p class="form-label text-justify font-italic">Modificacion de tutores asignado al alumno.</p>
    	</div>
    </div>
     <form class="mt-3 container form-horizontal" onkeypress="if(event.keyCode == 13) event.returnValue = false;" action="/Actualizar/Tutores" method="POST">
     	{% csrf_token %}
     	
     	<div class="form-inline form-group">
        	<label class="text-right justify-content-end control-label col-sm-2">Alumno:</label> 
        	<input type="text" class="form-control col-sm-10" name="alu_nombre" value="{{Alumno.alu_nombre}}" readonly="" />
        </div>
        <div class="form-inline form-group">
            <label class="text-right justify-content-end control-label col-sm-2">Tutores:</label>
            <div class="form-inline form-group col-sm-10">
            <div class="p-3">
            <div style="display: none;">
                <input type="text" name="slug" value="{{Alumno.slug}}" />
                <input type="text" id="alu_tutores" name="alu_tutores" value="" />
                <ul required="" id="id_alu_tutores" multiple="multiple">
                    {% for alm in Alumno.alu_tutores.all %}
                    <li>{{alm}}</li>
                {% endfor %}
                </ul>
            </div>
            <table id="tableNombreTutores">
                <thead></thead>
                <tbody>
                    
                {% for alm in Padres %}
                    <tr><td>{{alm.Nombre}} {{ alm.Apellidos}}</td></tr>
                {% endfor %}
                </tbody>
            </table>
            <label id="totalTutores"></label>
        </div>
    </div>
</div>
    <div  class="form-inline form-group" >
        <label class="text-right justify-content-end control-label col-sm-2">Asignar tutores</label> 
        <div class="form-inline form-group col-sm-10">
            <input type="text" class="form-control" placeholder="Buscar por nombre" title="Precione la tecla 'enter' para buscar" id="inputBusqueda" onkeypress="busquedaEnter(event)"/> 
            <table id="tableTutores" class="table table-bordered mt-1">
                    <thead>
                        <tr>
                            <th>Usuario</th>
                            <th>Nombre</th>
                            <th>--</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>

            
        </div>
        </div>
        <div class="form-group ">
          <div class="d-flex justify-content-around">
            <button  class="btn btn-success" type="submit">Guardar</button>
            <button class="btn btn-danger" onclick="window.location.href = '/'" type="reset">Cancelar</button>
        </div>
    </div>
     </form>
</div>
<script type="text/javascript">
    var total = 0;
    
function Buscar(){
    var valor = document.getElementById('inputBusqueda').value;
    var x = new XMLHttpRequest();
    x.open('GET','/tutores/busqueda/?filtro=' + valor)
    x.onreadystatechange = function (e) {
    if (x.readyState == 4) {
        if (x.status === 200) {
            x.addEventListener('load', function(e){
                var jsonData = JSON.parse(x.responseText.replace(/\'/g,'"'))
                iterarObjeto(jsonData);
            });
        } else {
            console.error(x.status);
            }
    }
    }
    x.send();
}
  
function busquedaEnter(e){
    if(e.keyCode == 13){
        Buscar();
    }
}
var js 
function iterarObjeto(obj){
    document.getElementById('tableTutores').children[1].innerHTML = '';
    for(i = 0; i < obj.length; i++){

        var span = validar(obj[i].Usuario)
        var tr = document.createElement('tr');
        tr.innerHTML ='<td>' + obj[i].Usuario + '</td>'+
            '<td>' + obj[i].Apellidos + '</td>'+
            '<td '+ span +'</td>';
        document.getElementById('tableTutores').children[1].appendChild(tr);
    }
}    

function SetTutor(itm){
    var sl = document.getElementById('id_alu_tutores')
    var opt = document.createElement('li')
    opt.innerHTML = itm.parentNode.children[0].innerHTML
    sl.appendChild(opt);
    
    var tbl = document.getElementById('tableNombreTutores').children[1]
    var tr = document.createElement('tr')
    tr.innerHTML = '<td>' + itm.parentNode.children[1].innerHTML + '</td>'
    tbl.appendChild(tr);
    countTutores();
    actualizarArray();
    Buscar()
}

function rmTutor(itm){
    var sl = document.getElementById('id_alu_tutores')
    var tbl = document.getElementById('tableNombreTutores').children[1]
    var usuario = itm.parentNode.children[0].innerHTML;
    var nombre = itm.parentNode.children[1].innerHTML;
    for(var i = 0; i < sl.childElementCount; i++){
          if(sl.children[i].textContent == usuario){
            sl.children[i].remove();
          }
    }
    for(var i = 0; i < tbl.rows.length; i++){
        if (tbl.children[i].children[0].innerText == nombre) {
            tbl.children[i].remove();
        }
    }
    countTutores();
    actualizarArray()
    Buscar()
}

function countTutores(){
    total = document.getElementById('id_alu_tutores').childElementCount;
    document.getElementById('totalTutores').textContent = 'Tutores seleccionados: ' + total;
}

function validar(usuario){
    var span ='>--';
    var encontrado = false;
    var sl = document.getElementById('id_alu_tutores')
    for(var i = 0; i < sl.childElementCount; i++){
        if(sl.children[i].textContent == usuario){
            span = 'onclick="rmTutor(this)" class="text-center"><span style="color: red;" class="oi oi-trash"></span>'
            encontrado = true;
        }   
    }
    if (total < 3 && !encontrado){
        span = 'onclick="SetTutor(this)" class="text-center" ><span style="color: mediumseagreen;" class="oi oi-plus"></span></span>'
    }

    return span;
}
var json = '';
function actualizarArray(){
    var sl = document.getElementById('id_alu_tutores')
    json = '[';
        for(var i = 0; i < sl.childElementCount; i++){
            json +=(i ==0)? '{"Usuario":"':',{"Usuario":"';
            json += sl.children[i].textContent;
            json += '"}'
        }
        json += "]"
        document.getElementById('alu_tutores').value = json
}

countTutores()
Buscar()
actualizarArray()
</script>
{% endblock %}

templates/alumnos/detalleAlumno.html
{% extends "base.html" %}
{% block title %}Informacion del alumno{% endblock %}
{% block content %}
<div class="container">

<div class="mt-4 mb-4 card border rounded border-warning" style="max-width:300px">
<img src="{{ object.alu_foto.url }}" class="card-img-top border-bottom"/>
    <div class="card-body border-bottom">
<h3 class="form-label text-center">Alumno</h3>
    </div>
    <div class="card-body">
        <div class="form-inline form-group">
            <h4 class="card-title">{{object.alu_nombre}}</h4>
            <h5 class="w-100"> {{object.alu_genero}}</h5>
            <h6>Fecha de ingreso: {{object.alu_fechaIngreso}}</h6>
            <p class="card-text">{{object.alu_observaciones}}</p>
        </div>
    </div>

</div>
<button class="btn btn-danger" onclick="window.location.href = '/alumnos/detalles'">Volver</button>
</div>
{% endblock %}

templates/alumnos/evaluar.html
{% extends 'base.html' %}
{% load staticfiles %}
	{%block title %} 
		Formulario Alumno
	{% endblock %}

	{% block content%}
<div class="mt-3 mb-4 card border rounded border-warning">
    <div class="card-body border-bottom">
<h2 class="form-label text-center">Evaluacion Semanal </h2>
<p class="form-label text-justify font-italic">Evalua al alumno.</p>
<p style="color:red;" class="form-label text-justify font-italic">Calificar con 1 si el alumno no lo hace.</p>
<p style="color:blue;" class="form-label text-justify font-italic">Calificar con 2 si el frecuentemente lo hace</p>
<p style="color:green;" class="form-label text-justify font-italic">Calificar con 3 si el alumno lo hace muy frecuentemente</p>


    </div>
<form class="mt-3 container form-horizontal" method="POST">
{% csrf_token %}
    
    {% for field in form %}
     <div class="form-inline form-group">
    {% if field.name == 'E_fecha' %}
    <label class="text-right justify-content-end control-label col-sm-2" for="{{ field.name }}">{{ field.label }}</label>
    {{field}}
    {% elif field.name == 'E_maestro' %}
    <label class="text-right justify-content-end control-label col-sm-2" for="{{ field.name }}">{{ field.label }}</label>
    <input class="form-control col-sm-2"  readonly="True" id="{{field.id}}" name="{{field.name}}" text="asd" value="{{user.id}}" required hidden="True" />
    <input class="form-control col-sm-2"  readonly="True" id="{{field.id}}" name="copiaxp" text="asd" value="{{user.username}}" required />

    {% elif field.name == 'E_alumno' %}
    <label class="text-right justify-content-end control-label col-sm-2" for="{{ field.name }}">{{ field.label }}</label>
    <input class="form-control col-sm-2"  readonly="True" id="id={{field.id}}" name="{{field.name}}" value="{{alumno}}" required />
    {% else %}
    <label class="text-right justify-content-end control-label col-sm-5" for="{{ field.name }}">{{ field.label }}</label>
    {{field}}
    {% endif %}
    </div>
    {% endfor %}
      <div class="form-group ">
          <div class="d-flex justify-content-around">
            <button class="btn btn-success" type="submit">Registrar</button>
            <button class="btn btn-danger" type="reset">Limpiar campos</button>
          </div>
    </div>
</form>
</div>
{% endblock %}

templates/alumnos/evaluarDiario.html
{% extends 'base.html' %}
{% load staticfiles %}
	{%block title %} 
		Formulario Alumno
	{% endblock %}

	{% block content%}
<div class="mt-3 mb-4 card border rounded border-warning">
    <div class="card-body border-bottom">
<h2 class="form-label text-center">Diario de trabajo</h2>
<p class="form-label text-justify font-italic">Evalua al alumno.</p>


    </div>
<form class="mt-3 container form-horizontal" method="POST">
{% csrf_token %}
    
    {% for field in form %}
     <div class="form-inline form-group">
    {% if field.name == 'DT_fecha' %}
    <label class="text-right justify-content-end control-label col-sm-2" for="{{ field.name }}">{{ field.label }}</label>
    {{field}}
    {% elif field.name == 'DT_maestro' %}
    <label class="text-right justify-content-end control-label col-sm-2" for="{{ field.name }}">{{ field.label }}</label>
    <input class="form-control col-sm-2"  readonly="True" id="{{field.id}}" name="{{field.name}}" text="asd" value="{{user.id}}" required hidden="True" />
    <input class="form-control col-sm-2"  readonly="True" id="{{field.id}}" name="copiaxp" text="asd" value="{{user.username}}" required />

    {% elif field.name == 'DT_alumno' %}
    <label class="text-right justify-content-end control-label col-sm-2" for="{{ field.name }}">{{ field.label }}</label>
    <input class="form-control col-sm-2"  readonly="True" id="id={{field.id}}" name="{{field.name}}" value="{{alumno}}" required />
    {% else %}
    <label class="text-right justify-content-end control-label col-sm-5" for="{{ field.name }}">{{ field.label }}</label>
    {{field}}
    {% endif %}
    </div>
    {% endfor %}
      <div class="form-group ">
          <div class="d-flex justify-content-around">
            <button class="btn btn-success" type="submit">Registrar</button>
            <button class="btn btn-danger" type="reset">Limpiar campos</button>
          </div>
    </div>
</form>
</div>
{% endblock %}