prescolapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth.views import logout_then_login
from alumnos.views import Index ,AlumnoCreate, AlumnoReporte, busquedaTurores,ReporteNoChafa, busquedaAlumno,Detail_ninja, Update_Alumno, Detail_Alumno, AgregarAlumConEstilo, EvaluarAlumno, EvaDiario, detalleEvalSem, detalleDiario, DiarioReporte, EvaluacionReporte, reporteEvaluacionAlumno, reporteDiarioAlumno
from maestros.views import agregarMaestro, actualizarMaestro, MaestroReporte, buscarMaestros,DetalleMaestro, crearGrupo, buscarSinGrupo, buscarGrupo, GrupoReporte, infoGrupo, actualizaGrupo,buscarEnelGrupo
from padres.views import LogIn, Index2, login, addTutor, tutorAsign,updateTutores, TutoresReporte, Detail_Tutor, ActualizarTutores
#para las fotos
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'login/', login, name='login'),
    url(r'^$',Index, name='index'),
    url(r'^index2',Index2, name='index2'),
    #url para alumnos 
    url(r'^alumnos/detalles',AlumnoReporte.as_view(),name='alumnos_reporte'),
    url(r'^alumnos/agregar',AgregarAlumConEstilo.as_view(),name='alumnos_agregarxd'),
    #url(r'^alumnos/agregar2',AlumnoCreate.as_view(),name='alumnos_agregar'),
    url(r'^alumnos/paginador',ReporteNoChafa.as_view(),name='alumnos_pagina'),
    url(r'^cerrar', logout_then_login, name='logout' ),
    #url(r'^maestros/agregar', StudentSignUpView.as_view(), name='student_signup'),
    url(r'^tutores/busqueda',busquedaTurores,name='filtroTutores'),
    url(r'^alumnos/Buscar', busquedaAlumno, name='filtroAlumno'),
    path('detalleAlumno/<slug:slug>', Detail_ninja.as_view(), name='detail_view' ),
    url(r'^maestros/nuevo', agregarMaestro.as_view(), name="add_teacher"),
    url(r'^padres/agregar', addTutor.as_view(), name="AddTutor"),
    path('updateAlumno/<slug:slug>', Update_Alumno.as_view(), name="UpdateAlumno"),
    path('detalles/<slug:slug>', Detail_Alumno.as_view()),
    path('evaluar/<slug:slug>', EvaluarAlumno.as_view()),
    path('diario/<slug:slug>', EvaDiario.as_view()),
    path('addtutor/<slug:slug>', tutorAsign),
    path('Actualizar/Tutores', updateTutores),
    path('tutor/buscar', TutoresReporte.as_view(), name='reporteTutor'),
    path('detalles/tutor/<slug:slug>', Detail_Tutor),
    path('actualiza/tutor/<slug:slug>', ActualizarTutores),
    path('actualiza/maestro/<slug:slug>',actualizarMaestro),
    path('maestro/buscar', MaestroReporte.as_view(), name='reporteMaestro'),
    path('detalles/maestro/<slug:slug>', DetalleMaestro),
    path('maestros/busqueda/', buscarMaestros),
    path('grupo/crear', crearGrupo, name='crearGrupo'),
    path('alumnosNG/busqueda/', buscarSinGrupo),
    path('grupos/busqueda/', buscarGrupo),
    path('grupo/buscar', GrupoReporte.as_view(), name='reporteGrupo'),
    path('detalles/grupos/<slug:slug>',infoGrupo),
    path('actualiza/grupo/<slug:slug>', actualizaGrupo ),
    path('buscar/alumnosSG/<slug:slug>/', buscarEnelGrupo),
	path('detalle/evaluacion/semanal/<slug:slug>', detalleEvalSem),
    path('detalle/evaluacion/diario/<slug:slug>', detalleDiario),
    url(r'^reporte/diario', DiarioReporte.as_view(),name="reporteDiario"),
    url(r'^reporte/evaluacion', EvaluacionReporte.as_view(),name="reporteEvaluacion"),
    path('reporte/evallu/<slug:slug>', reporteEvaluacionAlumno),
    path('reporte/diarioalu/<slug:slug>', reporteDiarioAlumno),
    ]
#para las fotos
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

maestros/models.py
from django.db import models
from alumnos.models import alumnos
from padres.models import Profesor
from django.db.models.manager import EmptyManager


class grupos(models.Model):
    gru_clave = models.CharField(max_length = 10)
    gru_maestro = models.ForeignKey(Profesor, on_delete=models.CASCADE, blank=True, null=True, related_name="Maestro")
    gru_alumnos = models.ManyToManyField(alumnos)
    gru_salon = models.CharField(max_length = 10, default='')
    gru_grado = models.IntegerField(null=True)
    
    def __str__(self):
        return self.gru_clave
        
    
class DiarioTrabajo(models.Model):
    DT_maestro = models.ForeignKey(Profesor, on_delete = models.CASCADE)
    DT_alumno = models.ForeignKey(alumnos, on_delete= models.CASCADE)
    DT_fecha = models.DateField(auto_now_add = True)
    DT_descripcion = models.TextField()
    DT_actividadApoyo = models.TextField()
    DT_necesidades = models.TextField()

    def __str__(self):
        return str(self.DT_alumno)
    
class Evaluacion(models.Model):
    E_maestro = models.ForeignKey(Profesor, on_delete = models.CASCADE)
    E_alumno = models.ForeignKey(alumnos, on_delete = models.CASCADE)
    E_fecha = models.DateField(auto_now_add=True)
    #Desarrollo personal y social
    E_comparte = models.IntegerField(null=True)
    E_apoya = models.IntegerField(null=True)
    E_pregunta = models.IntegerField(null=True)
    E_sugerencia = models.IntegerField(null=True)
    E_controla = models.IntegerField(null=True)
    E_cuida = models.IntegerField(null=True)
    E_espera = models.IntegerField(null=True)
    E_negocia = models.IntegerField(null=True)
    E_trabajaEquipo = models.IntegerField(null=True)
    E_respeta = models.IntegerField(null=True)
    E_cuidadoso = models.IntegerField(null=True)
    E_involucra = models.IntegerField(null=True)
    E_iniciativa = models.IntegerField(null=True)
    E_riesgo = models.IntegerField(null=True)
    E_estrategias= models.IntegerField(null=True)
    E_seExpresa = models.IntegerField(null=True)
    #lenguaje y comunicacion 
    E_mencionaNombre = models.IntegerField(null=True)
    E_mencionaDomicilio = models.IntegerField(null=True)
    E_expresaSentir  = models.IntegerField(null=True)
    E_exprasaSentimientos = models.IntegerField(null=True)
    E_recuerdaSusesos = models.IntegerField(null=True)
    E_solicitaPalabra = models.IntegerField(null=True)
    E_respetaTurno = models.IntegerField(null=True)
    E_explica = models.IntegerField(null=True)
    E_formulaPreguntas = models.IntegerField(null=True)
    E_comprendeTareas = models.IntegerField(null=True)
    E_solicitaAyuda = models.IntegerField(null=True)
    E_conversa = models.IntegerField(null=True)
    E_expresaInformacion = models.IntegerField(null=True)
    E_escucha = models.IntegerField(null=True)
    E_narra = models.IntegerField(null=True)
    E_creaCuentos = models.IntegerField(null=True)
    E_memorizaPoemas = models.IntegerField(null=True)
    #pensamiento matematico
    E_realizaConteo = models.IntegerField(null=True)
    E_reconoce = models.IntegerField(null=True)
    E_plantea = models.IntegerField(null=True)
    E_sabeContar = models.IntegerField(null=True)
    E_sabeEscribir = models.IntegerField(null=True)
    E_izquierdaDerecha = models.IntegerField(null=True)
    E_arribaAbajo = models.IntegerField(null=True)
    E_llenoVacio = models.IntegerField(null=True)
    E_conoceDiasMeses = models.IntegerField(null=True)
    E_ayerMañana = models.IntegerField(null=True)
    #exploracion y conocimiento del mundo
    E_describeSeresVivos = models.IntegerField(null=True)
    E_identificaSeresVivos = models.IntegerField(null=True)
    E_describeFenomeno = models.IntegerField(null=True)
    E_clasifica = models.IntegerField(null=True)
    E_SigueNormas = models.IntegerField(null=True)
    E_manipula = models.IntegerField(null=True)
    E_pruebas = models.IntegerField(null=True)
    E_reconoceExperimento = models.IntegerField(null=True)
    E_expresaIdeas = models.IntegerField(null=True)
    E_establecePresePasa = models.IntegerField(null=True)
    E_comparteInformacion = models.IntegerField(null=True)
    E_identificaAmenazas = models.IntegerField(null=True)
    #expresion y apreciacion artistica
    E_escuchaYCanta = models.IntegerField(null=True)
    E_sigueRitmo = models.IntegerField(null=True)
    E_inventaCanciones = models.IntegerField(null=True)
    E_modifica = models.IntegerField(null=True)
    E_identificaDife = models.IntegerField(null=True)
    E_reproduceSecu = models.IntegerField(null=True)
    E_reconoceGeneroMu = models.IntegerField(null=True)
    E_baila = models.IntegerField(null=True)
    E_dramatizacion = models.IntegerField(null=True)
    E_participa = models.IntegerField(null=True)
    E_representa = models.IntegerField(null=True)
    E_improvisa = models.IntegerField(null=True)
    E_manipulaMateriales = models.IntegerField(null=True)
    E_observaRe = models.IntegerField(null=True)
    E_memorizaAutor = models.IntegerField(null=True)
    #desarollo fisico y salud 
    E_desplaza = models.IntegerField(null=True)
    E_muestra = models.IntegerField(null=True)
    E_participaJuegos = models.IntegerField(null=True)
    E_jalaEmpuja = models.IntegerField(null=True)
    E_explora = models.IntegerField(null=True)
    E_construye = models.IntegerField(null=True)
    E_arma = models.IntegerField(null=True)
    E_practica = models.IntegerField(null=True)
    E_conocePractica = models.IntegerField(null=True)
    E_conocePropone = models.IntegerField(null=True)
    E_reconoceAmbien = models.IntegerField(null=True)
    E_identificaPeligro = models.IntegerField(null=True)

maestros/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.contrib.auth.models import User
import datetime


class StudentSignUpForm(UserCreationForm):#forms.Form UserCreationForm
    nombres = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'class':'form-control', 'required': 'True'}))
    paterno = forms.CharField(label='Apellido Paterno:', widget=forms.TextInput(attrs={'class':'form-control','required' : 'True'}))
    materno = forms.CharField(label='Apellido Materno:', widget=forms.TextInput(attrs={'class':'form-control','required' : 'True'}))
    nacimiento = forms.CharField(label='Fecha de nacimiento:',initial=datetime.date.today, widget=forms.TextInput(attrs={'type':'date'}))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields
        
        widgets = {
            'username': forms.TextInput(attrs = {'class':'form-control'}),
            'password1': forms.PasswordInput(attrs = {'class' : 'form-control'}),
        }
        
        labels = {
            'username' : 'Usuario:',
            'password1': 'Contraseña',
        }

maestros/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.views import generic
from . import models 
from django.urls import reverse_lazy
from django.views.generic import CreateView, FormView
#example for diferent sessions
from .forms import StudentSignUpForm
from padres.models import Profesor
from django.contrib.auth.models import User, Permission
from django.http import JsonResponse, HttpResponse
from django.db.models import Q
from .models import grupos
from alumnos.models import alumnos
from django.core import serializers
import json

class agregarMaestro(FormView):
    template_name = 'maestros/addTeacher.html'
    form_class = StudentSignUpForm
    success_url =reverse_lazy('reporteMaestro')
    
    def form_valid(self, form):
        usr = form.save()
        prm = Permission.objects.get(codename='is_teacher')
        usr.user_permissions.add(prm)
        
        m = Profesor()
        m.pro_nombre = usr
        m.pro_nombres = form.cleaned_data['nombres']
        m.pro_apellidoPaterno = form.cleaned_data["paterno"]
        m.pro_apellidoMaterno = form.cleaned_data["materno"]
        m.pro_fechaNacimento = form.cleaned_data["nacimiento"]
        m.save()
        return super(agregarMaestro, self).form_valid(form)
        
def actualizarMaestro(request,slug):
    usr = User.objects.get(username = slug)
    maes = Profesor.objects.get(pro_nombre = usr)

    if request.method == 'POST':
        usr.set_password(request.POST['password1'])
        usr.save()

        maes.pro_nombres = request.POST['nombres']
        maes.pro_apellidoPaterno = request.POST['paterno']
        maes.pro_apellidoMaterno = request.POST['materno']
        maes.pro_fechaNacimento = request.POST['nacimiento']
        maes.save()

    ctx = {'Maestro':maes, 'Usuario': usr}
    return render(request, 'maestros/actualizamaestro.html', ctx)

class MaestroReporte(generic.ListView):
    template_name = 'maestros/reporte.html'
    model = Profesor

def buscarMaestros(request):
    if request.method == 'GET':
        datos = []
        filtro = request.GET['filtro']
        pfr = Profesor.objects.select_related().filter( Q(pro_nombres__contains = filtro) |Q(pro_apellidoMaterno__contains = filtro) |Q(pro_apellidoPaterno__contains = filtro))
        for x in pfr:
            datos.append({"Usuario":x.pro_nombre.username, "Nombre": (str(x.pro_nombres) + ' ' + str(x.pro_apellidoPaterno) + ' ' + str(x.pro_apellidoMaterno)), "Fecha": str(x.pro_fechaNacimento.strftime('%Y/%m/%d'))})

    else:
        datos = []

    return HttpResponse(str(datos))    

def DetalleMaestro(request, slug):
    usr = User.objects.get(username = slug)
    prf = Profesor.objects.get(pro_nombre = usr)
    grp = grupos.objects.select_related().filter(gru_maestro = prf)

    ctx = {"Usuario":usr, "Profesor": prf, "Grupos": grp}
    return render(request, 'maestros/detallemaestro.html', ctx)

def actualizaGrupo(request,slug):
    ng = grupos.objects.select_related().get(id=slug)
    maestro = Profesor.objects.exclude(pro_nombre = ng.gru_maestro.pro_nombre).all()
    if request.method == 'POST':
        us = User.objects.get(username= request.POST['maestro'])  
        mae = Profesor.objects.get(pro_nombre = us)
        ng.gru_clave = request.POST['clave']
        ng.gru_salon = request.POST['salon']
        ng.gru_maestro = mae
        ng.gru_grado = int(request.POST['grado'])
        ng.gru_alumnos.clear()
        ng.save()
        alms = json.loads(request.POST['alumnos'])
        for j in range(len(alms)):
            almSave = alumnos.objects.get(slug = alms[j]['slug'])    
            ng.gru_alumnos.add(almSave)
        ng.save()
    

    ng = grupos.objects.select_related().get(id = slug)
    maestro = Profesor.objects.exclude(pro_nombre = ng.gru_maestro.pro_nombre).all()
    alumnosGrupo = grupos.objects.select_related().get(id=slug)
    datosAlumnos = []
    for x in alumnosGrupo.gru_alumnos.all():
        datosAlumnos.append({"slug":x.slug, "Nombre": x.alu_nombre})

    ctx = {"Grupo":ng, "Maestro": ng.gru_maestro, "Profesores": maestro, "Alumnos": datosAlumnos}
    return render(request, 'grupos/actualizagrupo.html', ctx)        

def buscarEnelGrupo(request,slug):
    if request.method == 'GET':
        filtro = request.GET['filtro']
        almg = grupos.objects.select_related().exclude(id=slug).all()
        alm = []
        for ix in almg:
            for x in ix.gru_alumnos.all():
                alm.append(x.id)

        alumnosF = alumnos.objects.exclude(id__in = alm).filter(alu_nombre__contains = filtro)
        data = serializers.serialize('json', alumnosF)

    return HttpResponse(data)



def crearGrupo(request):
    if request.method == 'POST':
        ng = grupos()
        ng.gru_clave = request.POST['clave']
        ng.gru_salon = request.POST['salon']
        ng.gru_grado = int(request.POST['grado'])
        ng.save()
        alms = json.loads(request.POST['alumnos'])
        for i in range(len(alms)):
            addl = alumnos.objects.get(slug = alms[i]['slug'])
            ng.gru_alumnos.add(addl)

        ng.save()
        us = User.objects.get(username = request.POST['maestro'])
        pro = Profesor.objects.get(pro_nombre = us)
        ng.gru_maestro = pro;
        ng.save()


    gps = grupos.objects.select_related().all()
    maes = Profesor.objects.all()
    data = []
    for gp in gps:
        for alm in gp.gru_alumnos.all():
            data.append(alm.slug)
    

    alm = alumnos.objects.exclude(slug__in = data).all()
    return render(request, 'grupos/agregargrupo.html', {"Alumnos": alm, 'Maestros': maes})

def buscarSinGrupo(request):
    if request.method == 'GET':
        filtro = request.GET['filtro']
        gps = grupos.objects.select_related().all()
        alums = []
        for x in gps:
            for alm in x.gru_alumnos.all():
                alums.append(alm.slug)

        alm = alumnos.objects.exclude(slug__in =alums).filter(alu_nombre__contains = filtro)
        data = serializers.serialize('json',alm)

    return HttpResponse(data)

class GrupoReporte(generic.ListView):
    template_name = 'grupos/reporte.html'
    model = grupos

def buscarGrupo(request):
    if request.method == 'GET':
        filtro = request.GET['filtro']
        grp = grupos.objects.select_related().filter(Q(gru_salon__contains = filtro) |Q(gru_clave__contains = filtro))
        tut = []
        for x in grp:
            tut.append({"Tutor": str(x.gru_maestro.pro_nombres + ' ' + x.gru_maestro.pro_apellidoPaterno), "Clave": x.gru_clave, "Salon": x.gru_salon, "Grado": x.gru_grado, "Id": x.id, "Alumnos": len(x.gru_alumnos.all())})

    return HttpResponse(str(tut))

def infoGrupo(request, slug):
    grp = grupos.objects.select_related().get(id = slug)
    ctx = {"Grupo": grp, "Alumnos": grp.gru_alumnos.all(), "Profesor": grp.gru_maestro}
    return render(request, 'grupos/detallegrupo.html', ctx)

templates/maestros/actualizamaestro.html
{% extends 'base.html' %}
{% block title %}Actualizar maestro{% endblock %}
{% block content %}
<div id="alert" class="alert-dismissible">
  <label class="close" onclick="cerrarAlerta()" >&times;</label>
  <strong id="msgAlert"></strong> <label id="msglblAlert"></label>
</div>
<div class="mt-3 mb-4 card border rounded border-warning">
    <div class="card-body border-bottom">
<h2 class="form-label text-center">Editar maestro</h2>
<p class="form-label text-justify font-italic">Edita el usuario del maestro.</p>
    </div>
<form class="mt-3 container form-horizontal" method="POST" onsubmit="return valida()">
{% csrf_token %}
    
      <div class="form-inline form-group">
    
    <label class="text-right justify-content-end control-label col-sm-2" for="username">Usuario:</label>
          <input class="form-control col-sm-10" value="{{Usuario.username}}" name="username" required="" readonly="">
    </div>
    
      <div class="form-inline form-group">
    
    <label class="text-right justify-content-end control-label col-sm-2" for="password1">Contraseña:</label>
          <input class="form-control col-sm-10" type="password" id="password1" name="password1" required="">
    
    </div>
    
      <div class="form-inline form-group">
    
    <label class="text-right justify-content-end control-label col-sm-2" for="password2">Confirmar contraseña:</label>
          <input class="form-control col-sm-10" type="password" id="password2" name="password2" required="">
    
    </div>
    
      <div class="form-inline form-group">
    
    <label class="text-right justify-content-end control-label col-sm-2" for="nombres">Nombres:</label>
          <input class="form-control col-sm-10" id="nombres" value="{{Maestro.pro_nombres}}" name="nombres" required="">
    
    </div>
    
      <div class="form-inline form-group">
    
    <label class="text-right justify-content-end control-label col-sm-2" for="paterno">Apellido Paterno:</label>
          <input class="form-control col-sm-10" id="paterno" value="{{Maestro.pro_apellidoPaterno}}" name="paterno" required="">
    </div>
    
      <div class="form-inline form-group">
    
    <label class="text-right justify-content-end control-label col-sm-2" for="materno">Apellido Materno:</label>
          <input class="form-control col-sm-10" name="materno" value="{{Maestro.pro_apellidoMaterno}}" required="">
    
    </div>
    
      <div class="form-inline form-group">
    
    <label class="text-right justify-content-end control-label col-sm-2" for="nacimiento">Fecha de nacimiento:</label>
    <input type="date" name="nacimiento" class="form-control" value="{{Maestro.pro_fechaNacimento|date:"Y-m-d"}}" required="" id="id_nacimiento">
    
    </div>
      <div class="form-group ">
          <div class="d-flex justify-content-around">
            <button class="btn btn-success" type="submit">Actualizar</button>
            <button class="btn btn-danger" type="button">Cancelar</button>
          </div>
    </div>
</form>
</div>
<script type="text/javascript">
function valida(){
	var ok = true;
	var ps1 = document.getElementById('password1').value
	var ps2 = document.getElementById('password2').value
	if (ps1 != ps2) { ok = false
		document.getElementById('msgAlert').textContent = 'Contraseña'
		document.getElementById('msglblAlert').textContent = 'Las contraseñas no coinciden.'
		document.getElementById('alert').classList.add('alert')
		document.getElementById('alert').classList.add('alert-warning')
	}


	return ok;
}
function cerrarAlerta(){
	document.getElementById('alert').classList.remove('alert')
	document.getElementById('alert').classList.remove('alert-warning')
	document.getElementById('msglblAlert').textContent = ''
	document.getElementById('msgAlert').textContent = '	'

}
</script>
{% endblock %}

templates/maestros/addTeacher.html
{% extends 'base.html' %}
{% block title%}Agregar maestro{% endblock %}
{% block content %}
<div class="mt-3 mb-4 card border rounded border-warning">
    <div class="card-body border-bottom">
<h2 class="form-label text-center">Agregar maestro</h2>
<p class="form-label text-justify font-italic">Crea un usuario nuevo para un maestro.</p>
    </div>
<form class="mt-3 container form-horizontal" method="POST">
{% csrf_token %}
    {% for field in form %}
      <div class="form-inline form-group">
    {% if field.name == 'password1' %}
    <label class="text-right justify-content-end control-label col-sm-2" for="{{ field.name }}">Contraseña:</label>
          <input class="form-control col-sm-10" type="password" id="{{field.id}}" name="{{field.name}}" required />
    {% elif field.name == 'password2' %}
    <label class="text-right justify-content-end control-label col-sm-2" for="{{ field.name }}">Confirmar contraseña:</label>
          <input class="form-control col-sm-10" type="password" id="{{field.id}}" name="{{field.name}}" required />
    {% elif field.name == 'nacimiento' %}
    <label class="text-right justify-content-end control-label col-sm-2" for="{{ field.name }}">{{ field.label }}</label>
    {{field}}
    {% else %}
    <label class="text-right justify-content-end control-label col-sm-2" for="{{ field.name }}">{{ field.label }}</label>
          <input class="form-control col-sm-10" id="{{field.id}}" name="{{field.name}}" required />
    {% endif %}
    </div>
    {% endfor %}
      <div class="form-group ">
          <div class="d-flex justify-content-around">
            <button class="btn btn-success" type="submit">Registrar</button>
            <button class="btn btn-danger" type="reset">Limpiar campos</button>
          </div>
    </div>
</form>
</div>
    <!--
    <div style="width: 50%;">
    </div>
    <div style="width: 50%; float: left;">
        <div style="width: 100%;">
        <label>Apellido paterno:</label>
    {{form.paterno}}
        </div>
        <p>
        <label>Apellido materno:</label>
        {{form.materno}}
        </p>
    </div>
-->

{% endblock %}

templates/maestros/create.html
{% extends 'base.html' %}

	{%block title %} 
		Formulario Alumno
	{% endblock %}

	{% block content%}
	
	<h1>Formulario de prueba para maestros</h1>
	    {% block main %}
    <form action="" enctype="multipart/form-data" method="POST"><input name="csrfmiddlewaretoken" value="8gIPdFQ3qED0ZvCrgfSgcKT5YeFJXMufosYbpNKl0RdTfU5xwTjSLnWyeFCnTkZ8" type="hidden">
    <table>
 		<tbody><tr><th><label for="id_mae_nombre">Mae nombre:</label></th><td><select name="mae_nombre" id="id_mae_nombre" required="">
  		<option value="" selected="">---------</option>

  		<option value="1">admin</option>

  		<option value="2">alflo</option>

  		<option value="3">AlexSB664</option>

  		<option value="4">Daniel</option>

		</select></td></tr>
		<tr><th><label for="id_mae_apellidoPaterno">Mae apellidoPaterno:</label></th><td><input name="mae_apellidoPaterno" maxlength="70" id="id_mae_apellidoPaterno" required="" type="text"></td></tr>
		<tr><th><label for="id_mae_apellidoMaterno">Mae apellidoMaterno:</label></th><td><input name="mae_apellidoMaterno" maxlength="70" id="id_mae_apellidoMaterno" required="" type="text"></td></tr>
		<tr><th><label for="id_mae_fechaNacimento">Mae fechaNacimento:</label></th><td><input name="mae_fechaNacimento" id="id_mae_fechaNacimento" required="" type="text"></td></tr>   
        </tbody>
    </table>
    <input name="crear" value="Crear" type="submit">
    </form> <br>
    {% endblock main %}

{% endblock %}